"""
Django settings for myfirst project.

Generated by 'django-admin startproject' using Django 4.2.16.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import sys
from pathlib import Path
from decouple import config
from django.core.exceptions import ImproperlyConfigured


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Detect execution context
IS_RUNNING_TESTS = 'test' in sys.argv
IS_RUNNING_DEV_SERVER = 'runserver' in sys.argv

# SECURITY WARNING: don't run with debug turned on in production!
# Secure by default: DEBUG is False unless explicitly set to True/1
raw_debug = config('DJANGO_DEBUG', default=None)
if raw_debug is not None:
    DEBUG = str(raw_debug).strip().lower() in ('true', '1', 'yes', 'on', 't')
else:
    debug_val = config('DEBUG', default=None)
    if debug_val is not None:
        DEBUG = str(debug_val).strip().lower() in ('true', '1', 'yes', 'on', 't')
    else:
        # Secure by default: False for WSGI/production/deployment, True for local dev server
        DEBUG = True if IS_RUNNING_DEV_SERVER else False

# SECURITY WARNING: keep the secret key used in production secret!
# Fail hard if SECRET_KEY is not set when running in production (DEBUG=False)
SECRET_KEY = config('SECRET_KEY', default='')
if not SECRET_KEY:
    if DEBUG or IS_RUNNING_TESTS or IS_RUNNING_DEV_SERVER:
        SECRET_KEY = 'django-insecure-development-test-key-do-not-use-in-production-css-society-2026'
    else:
        raise ImproperlyConfigured(
            "SECRET_KEY environment variable must be set in production when DEBUG=False."
        )

ALLOWED_HOSTS = ['localhost', '127.0.0.1', '.onrender.com', 'testserver']
RENDER_EXTERNAL_HOSTNAME = config('RENDER_EXTERNAL_HOSTNAME', default=None)
if RENDER_EXTERNAL_HOSTNAME:
    ALLOWED_HOSTS.append(RENDER_EXTERNAL_HOSTNAME)

CSRF_TRUSTED_ORIGINS = [
    'https://*.onrender.com',
]

# Security Headers & Reverse-Proxy Configuration
# Render terminates SSL at reverse proxy and forwards proto
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# SSL Redirect: redirect HTTP to HTTPS in production
SECURE_SSL_REDIRECT = config('SECURE_SSL_REDIRECT', default=(not DEBUG and not IS_RUNNING_TESTS), cast=bool)

# Cookie Security
SESSION_COOKIE_SECURE = config('SESSION_COOKIE_SECURE', default=(not DEBUG and not IS_RUNNING_TESTS), cast=bool)
CSRF_COOKIE_SECURE = config('CSRF_COOKIE_SECURE', default=(not DEBUG and not IS_RUNNING_TESTS), cast=bool)

# HTTP Strict Transport Security (HSTS)
if not DEBUG and not IS_RUNNING_TESTS:
    SECURE_HSTS_SECONDS = config('SECURE_HSTS_SECONDS', default=31536000, cast=int)
    SECURE_HSTS_INCLUDE_SUBDOMAINS = config('SECURE_HSTS_INCLUDE_SUBDOMAINS', default=True, cast=bool)
    SECURE_HSTS_PRELOAD = config('SECURE_HSTS_PRELOAD', default=True, cast=bool)
else:
    SECURE_HSTS_SECONDS = 0
    SECURE_HSTS_INCLUDE_SUBDOMAINS = False
    SECURE_HSTS_PRELOAD = False

# Content sniffing and frame defense
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = 'DENY'


# Application definition

INSTALLED_APPS = [
    'users.apps.UsersConfig',
    'crispy_forms',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'crispy_bootstrap4',
    'homepage',
    'crispy_bootstrap5',
    'executives',
    'activities',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'myfirst.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'homepage.context_processors.site_settings',
            ],
        },
    },
]

WSGI_APPLICATION = 'myfirst.wsgi.application'


# Database
# ─────────────────────────────────────────────────────────────────────────────
# Production (Render): set the DATABASE_URL environment variable to the
# internal connection string from your Render PostgreSQL database.
# Local development: falls back to SQLite so no extra setup is needed.
DATABASE_URL = config('DATABASE_URL', default='')

if DATABASE_URL:
    # Parse postgres://user:pass@host:port/dbname  (Render provides this format)
    import urllib.parse as _urlparse
    _url = _urlparse.urlparse(DATABASE_URL)
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': _url.path.lstrip('/'),
            'USER': _url.username,
            'PASSWORD': _url.password,
            'HOST': _url.hostname,
            'PORT': _url.port or 5432,
            'OPTIONS': {
                'sslmode': 'require',   # Render requires SSL on external connections
            },
            'CONN_MAX_AGE': 60,         # Reuse connections for 60 s (reduces overhead)
        }
    }
else:
    # Local development — SQLite, no extra setup needed
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = '/static/'
# TODO(security-audit): Static image assets are duplicated between homepage/static/ and root static/.
# Consolidate into a single static directory to reduce repo footprint and avoid build conflicts.
STATICFILES_DIRS = [BASE_DIR / "homepage/static"]
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATIC_ROOT.mkdir(exist_ok=True)
STATICFILES_STORAGE = 'whitenoise.storage.CompressedStaticFilesStorage'
CRISPY_TEMPLATE_PACK = 'bootstrap4'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'



CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Redirect to the home page or any other page after login
LOGIN_REDIRECT_URL = ''
LOGIN_URL = 'login'

# ─── Email Configuration ────────────────────────────────────────────────────
# Brevo (formerly Sendinblue) SMTP relay is used for transactional emails.
# Set BREVO_API_KEY and BREVO_SMTP_LOGIN in your .env to enable real sending.
# Without the key the app falls back to console output (safe for local dev).
# Brevo supports port 587 (TLS) and port 2525 (TLS alternative if host blocks 587).
BREVO_API_KEY = config('BREVO_API_KEY', default='')
BREVO_SMTP_LOGIN = config('BREVO_SMTP_LOGIN', default='')
EMAIL_PORT = config('EMAIL_PORT', default=587, cast=int)
EMAIL_USE_TLS = config('EMAIL_USE_TLS', default=(EMAIL_PORT != 465), cast=bool)
EMAIL_USE_SSL = config('EMAIL_USE_SSL', default=(EMAIL_PORT == 465), cast=bool)
EMAIL_TIMEOUT = config('EMAIL_TIMEOUT', default=10, cast=int)

if BREVO_API_KEY and BREVO_SMTP_LOGIN:
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
    EMAIL_HOST = config('EMAIL_HOST', default='smtp-relay.brevo.com')
    EMAIL_HOST_USER = BREVO_SMTP_LOGIN    # Your Brevo account email address
    EMAIL_HOST_PASSWORD = BREVO_API_KEY   # Your Brevo SMTP key (from Brevo → SMTP & API)
    DEFAULT_FROM_EMAIL = config(
        'DEFAULT_FROM_EMAIL',
        default=f'CSS Society <{BREVO_SMTP_LOGIN}>'
    )
    SERVER_EMAIL = DEFAULT_FROM_EMAIL
else:
    # Fallback: print emails to terminal during local dev; require SMTP in prod
    EMAIL_BACKEND = config(
        'EMAIL_BACKEND',
        default=(
            'django.core.mail.backends.console.EmailBackend'
            if DEBUG
            else 'django.core.mail.backends.smtp.EmailBackend'
        ),
    )
    EMAIL_HOST = config('EMAIL_HOST', default='smtp-relay.brevo.com')
    EMAIL_HOST_USER = config('EMAIL_HOST_USER', default='')
    EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD', default='')
    DEFAULT_FROM_EMAIL = config('DEFAULT_FROM_EMAIL', default='noreply@localhost')
    SERVER_EMAIL = DEFAULT_FROM_EMAIL


# reCAPTCHA Configuration
# Google provides official test keys which always pass for local dev:
# Site key: 6LeIxAcTAAAAAJcZVRqyHh71UMIEGNQ_MXjiZKhI
# Secret key: 6LeIxAcTAAAAAGG-vFI1TnRWxMZNFuojJ4WifJWe
RECAPTCHA_ENABLED = config('RECAPTCHA_ENABLED', default=True, cast=bool)
RECAPTCHA_SITE_KEY = config('RECAPTCHA_SITE_KEY', default='6LeIxAcTAAAAAJcZVRqyHh71UMIEGNQ_MXjiZKhI')
RECAPTCHA_SECRET_KEY = config('RECAPTCHA_SECRET_KEY', default='6LeIxAcTAAAAAGG-vFI1TnRWxMZNFuojJ4WifJWe')

# Terminal & Server Logging Configuration
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '[{asctime}] {levelname} [{name}] {message}',
            'style': '{',
            'datefmt': '%Y-%m-%d %H:%M:%S',
        },
        'server': {
            'format': '[{asctime}] {message}',
            'style': '{',
            'datefmt': '%H:%M:%S',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'stream': sys.stdout,
            'formatter': 'verbose',
        },
        'server_console': {
            'class': 'logging.StreamHandler',
            'stream': sys.stdout,
            'formatter': 'server',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'django.server': {
            'handlers': ['server_console'],
            'level': 'INFO',
            'propagate': False,
        },
        'django.request': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'users': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'homepage': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}

