services:
  - type: web
    name: css-society
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn myfirst.wsgi:application"
    envVars:
      - key: DJANGO_DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: "4"
        fromDatabase:
          name: css-society-db
          property: connectionString
databases:
  - name: css-society-db
    databaseName: css_society
    user: css_society
    plan: free
