# Generated by Django 4.2.16 on 2025-01-21 15:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='banner_image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='activities/banner'),
            preserve_default=False,
        ),
    ]
