# Generated by Django 4.2.16 on 2025-01-21 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_event_banner_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='activity',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
    ]
