# Generated by Django 4.2.16 on 2025-01-23 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0003_event_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='banner_image',
            field=models.ImageField(upload_to='activities/banner/'),
        ),
    ]
