# Generated by Django 4.2.16 on 2025-01-23 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0004_alter_event_banner_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='banner_image',
            field=models.ImageField(upload_to='events/images/'),
        ),
    ]
