# Generated by Django 4.2.16 on 2024-12-02 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('executives', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='executive',
            name='academic_year',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='executive',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='executive',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
