# Generated by Django 4.2.16 on 2024-12-16 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('executives', '0002_alter_executive_academic_year_alter_executive_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='executive',
            old_name='title',
            new_name='position',
        ),
        migrations.RemoveField(
            model_name='executive',
            name='image',
        ),
        migrations.RemoveField(
            model_name='executive',
            name='linkedin',
        ),
        migrations.RemoveField(
            model_name='executive',
            name='twitter',
        ),
        migrations.AlterField(
            model_name='executive',
            name='academic_year',
            field=models.CharField(max_length=50),
        ),
    ]
