# Generated by Django 4.2.16 on 2024-12-16 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('executives', '0003_rename_title_executive_position_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='executive',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='events/images/'),
        ),
    ]
