# Generated by Django 6.1.1 on 2026-09-17 13:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('category', models.CharField(choices=[('learning', 'Learning'), ('community', 'Community'), ('career', 'Career'), ('build', 'Build Log')], default='learning', max_length=50)),
                ('author_name', models.CharField(default='CSS Editorial Team', max_length=100)),
                ('author_role', models.CharField(default='CSS Contributor', max_length=100)),
                ('read_time', models.CharField(default='5 min read', max_length=50)),
                ('summary', models.TextField()),
                ('content', models.TextField()),
                ('image_path', models.CharField(default='images/AI.jpeg', max_length=200)),
                ('is_featured', models.BooleanField(default=False)),
                ('published_at', models.DateField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-is_featured', '-published_at'],
            },
        ),
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('category', models.CharField(choices=[('Design & Dev', 'Design & Development'), ('Build Log', 'Build Log & Systems'), ('Community', 'Community & Education'), ('Data Science', 'Data & Analytics'), ('Algorithms', 'Algorithms & Logic')], default='Design & Dev', max_length=50)),
                ('difficulty', models.CharField(choices=[('Beginner', 'Beginner Friendly'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], default='Beginner', max_length=50)),
                ('summary', models.TextField()),
                ('description', models.TextField()),
                ('requirements', models.TextField(help_text='Deliverables and guidelines for this challenge')),
                ('week_label', models.CharField(default='Week 04', max_length=50)),
                ('deadline_text', models.CharField(default='Submit by Sunday', max_length=100)),
                ('icon_class', models.CharField(default='bi-window-stack', max_length=50)),
                ('art_class', models.CharField(default='art-purple', max_length=50)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-is_featured', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Internship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('company', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('role_type', models.CharField(choices=[('Internship', 'Internship'), ('Part-time', 'Part-time'), ('Full-time', 'Full-time')], default='Internship', max_length=50)),
                ('duration', models.CharField(default='12 weeks', max_length=50)),
                ('description', models.TextField()),
                ('requirements', models.TextField(blank=True, default='')),
                ('tags', models.CharField(help_text='Comma-separated tags e.g. Python, React', max_length=200)),
                ('apply_url', models.URLField(blank=True, null=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('posted_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-is_featured', '-posted_at'],
            },
        ),
        migrations.CreateModel(
            name='NewsletterSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('subscribed_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CommunityMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('ai-ml', 'AI & Machine Learning'), ('web-cloud', 'Web & Cloud Systems'), ('cybersecurity', 'Cybersecurity & Ethical Hacking'), ('algorithms', 'Competitive Programming & Algorithms'), ('mobile', 'Mobile Apps & Engineering'), ('open-source', 'Open Source Collective')], default='ai-ml', max_length=50)),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChallengeSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_title', models.CharField(max_length=200)),
                ('repo_url', models.URLField(help_text='GitHub or code repository URL')),
                ('demo_url', models.URLField(blank=True, help_text='Optional live project URL', null=True)),
                ('description', models.TextField(help_text='Short explanation of how you solved the problem')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='homepage.challenge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenge_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submitted_at'],
                'unique_together': {('challenge', 'user')},
            },
        ),
    ]
