# Generated by Django 6.1.1 on 2026-09-17 14:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicAppointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_id', models.CharField(blank=True, max_length=30, unique=True)),
                ('full_name', models.CharField(max_length=150)),
                ('student_email', models.EmailField(max_length=254)),
                ('student_id', models.CharField(blank=True, default='', max_length=50)),
                ('department', models.CharField(default='Computer Science', max_length=100)),
                ('academic_year', models.CharField(default='Year 1', max_length=20)),
                ('device_brand', models.CharField(max_length=100)),
                ('device_model', models.CharField(max_length=100)),
                ('service_type', models.CharField(choices=[('linux', 'Linux Dual-Boot & OS Setup (Ubuntu / Fedora / Debian)'), ('dev-env', 'Developer Environment Setup (Docker, Python, Git, C++, VS Code)'), ('hardware', 'Hardware Diagnostics, Thermal Paste & Fan Cleaning'), ('malware', 'Malware Removal, Bloatware Cleanup & Security Hardening'), ('general', 'General Laptop Troubleshooting & Driver Support')], default='linux', max_length=50)),
                ('preferred_session', models.CharField(choices=[('2024-10-04', 'Wednesday, Oct 4, 2024 (2:00 PM – 5:30 PM) — Lab 204'), ('2024-10-06', 'Friday, Oct 6, 2024 (2:00 PM – 6:00 PM) — Lab 204'), ('2024-10-11', 'Wednesday, Oct 11, 2024 (2:00 PM – 5:30 PM) — Lab 204'), ('2024-10-13', 'Friday, Oct 13, 2024 (2:00 PM – 6:00 PM) — Lab 204'), ('2024-10-18', 'Wednesday, Oct 18, 2024 (2:00 PM – 5:30 PM) — Lab 204')], default='2024-10-04', max_length=50)),
                ('issue_description', models.TextField()),
                ('backup_acknowledged', models.BooleanField(default=False)),
                ('status', models.CharField(default='Confirmed', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clinic_appointments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
