# Generated by Django 6.1.1 on 2026-09-18 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_clinicappointment'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_code', models.CharField(help_text='Unique identifier e.g. 2024-10-04', max_length=50, unique=True)),
                ('date_title', models.CharField(help_text='e.g. Wednesday, Oct 4, 2024', max_length=120)),
                ('time_slot', models.CharField(default='2:00 PM – 5:30 PM', max_length=100)),
                ('venue', models.CharField(default='Software Lab 204, CS Building', max_length=150)),
                ('focus_topic', models.CharField(default='Linux Dual-Boot & OS Installation', max_length=255)),
                ('capacity', models.PositiveIntegerField(default=12)),
                ('leads', models.CharField(default='Student Tech Leads', max_length=200)),
                ('badge_text', models.CharField(blank=True, default='', max_length=80)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='InfoPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='guidelines, programs, terms, or privacy', unique=True)),
                ('title', models.CharField(max_length=150)),
                ('summary', models.TextField(blank=True, default='')),
                ('body', models.TextField(blank=True, default='', help_text='Optional custom body/content to supplement template content.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['slug'],
            },
        ),
    ]
