# Generated by Django 6.1.1 on 2026-09-18 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_clinicsession_infopage'),
    ]

    operations = [
        migrations.AddField(
            model_name='communitymessage',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='homepage.communitymessage'),
        ),
    ]
