# Generated by Django 6.1.1 on 2026-09-18 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0005_submissionupvote'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='e.g. ai-ml, web-cloud, cybersecurity', unique=True)),
                ('name', models.CharField(help_text='Channel name e.g. Future of AI & Machine Learning', max_length=150)),
                ('description', models.TextField(help_text='Channel purpose and track overview')),
                ('category', models.CharField(default='Technical Track', max_length=80)),
                ('icon_class', models.CharField(default='bi-cpu-fill', help_text='Bootstrap icon e.g. bi-cpu-fill, bi-cloud-arrow-up-fill', max_length=80)),
                ('accent_color', models.CharField(default='#2563EB', help_text='Hex color e.g. #4F46E5', max_length=20)),
                ('accent_bg', models.CharField(default='#EEF2FF', help_text='Hex bg e.g. #EEF2FF', max_length=20)),
                ('rail_class', models.CharField(default='rail-ai', help_text='Icon rail color class e.g. rail-ai, rail-web, rail-sec', max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Community Channel',
                'verbose_name_plural': 'Community Channels',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Computer Science Society', max_length=150)),
                ('hero_tagline', models.CharField(default='Official Student Chapter', max_length=200)),
                ('hero_title', models.CharField(default='Computer Science Society', max_length=200)),
                ('hero_description', models.TextField(default='Empowering students to learn, build, and lead in computing. Join specialized study cohorts, tackle hands-on weekly coding challenges, and connect with peer developers.')),
                ('announcement_active', models.BooleanField(default=True, help_text='Show or hide the top site announcement banner')),
                ('announcement_text', models.CharField(default='Upcoming CSS activities & workshops are now open for student registration!', max_length=255)),
                ('announcement_link_url', models.CharField(default='/activities/', max_length=200)),
                ('announcement_link_text', models.CharField(default='View Events', max_length=60)),
                ('contact_email', models.EmailField(default='css@knust.edu.gh', max_length=254)),
                ('github_url', models.URLField(blank=True, default='https://github.com')),
                ('linkedin_url', models.URLField(blank=True, default='https://linkedin.com')),
                ('twitter_url', models.URLField(blank=True, default='https://twitter.com')),
                ('instagram_url', models.URLField(blank=True, default='https://instagram.com')),
            ],
            options={
                'verbose_name': 'Site Configuration & Content',
                'verbose_name_plural': 'Site Configuration & Content',
            },
        ),
        migrations.AlterField(
            model_name='clinicappointment',
            name='preferred_session',
            field=models.CharField(default='2024-10-04', help_text='Clinic session code or date', max_length=100),
        ),
    ]
