# Generated by Django 6.1.1 on 2026-09-18 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0006_communitychannel_siteconfiguration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='communitychannel',
            name='image',
            field=models.ImageField(blank=True, help_text='Hub icon or badge image (1:1 square, max 2MB)', null=True, upload_to='community/channels/'),
        ),
    ]
