# Generated by Django 6.1.1 on 2026-09-19 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0007_communitychannel_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='allow_user_registration',
            field=models.BooleanField(default=True, help_text='Allow new students to register on the platform'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='lockout_duration_minutes',
            field=models.IntegerField(default=10, help_text='Cooldown duration in minutes after password reset'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='max_login_attempts',
            field=models.IntegerField(default=5, help_text='Number of failed logins before locking an account'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='recaptcha_enabled',
            field=models.BooleanField(default=True, help_text='Enable or disable Google reCAPTCHA v2 on forms'),
        ),
    ]
