# Generated by Django 6.1.1 on 2026-09-20 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0008_siteconfiguration_allow_user_registration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='require_email_verification',
            field=models.BooleanField(default=True, help_text='Require email verification before regular users can log in (admins are exempt)'),
        ),
    ]
