# Generated by Django 6.1.1 on 2026-09-21 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0009_siteconfiguration_require_email_verification'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='challenges_heading',
            field=models.CharField(default='Hands-on Coding Challenges', max_length=200),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='challenges_subheading',
            field=models.TextField(default='Sharpen your practical skills, build real projects, and showcase your code.'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='footer_about_text',
            field=models.TextField(default='The official student computing organization supporting student engineers, developers, and researchers.'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='guidelines_button_text',
            field=models.CharField(default='Read Community Guidelines', max_length=80),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='guidelines_description',
            field=models.TextField(default='We maintain an inclusive, supportive, and harassment-free environment for all computer science students across all physical and digital spaces.'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='guidelines_heading',
            field=models.CharField(default='Society Guidelines & Community Norms', max_length=200),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='newsletter_heading',
            field=models.CharField(default='Subscribe to the CSS Newsletter', max_length=200),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='newsletter_subheading',
            field=models.CharField(default='Stay updated on weekly challenge releases, campus workshops, and internship openings.', max_length=255),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='pillar1_description',
            field=models.TextField(default='Follow curated tracks from beginner syntax to production system architecture and cloud deployments.'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='pillar1_title',
            field=models.CharField(default='Learn', max_length=100),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='pillar2_description',
            field=models.TextField(default='Network with senior mentors, alumni engineers, and like-minded peers who share your career ambitions.'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='pillar2_title',
            field=models.CharField(default='Connect', max_length=100),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='pillar3_description',
            field=models.TextField(default='Expand your portfolio through hackathons, student tech clinics, and verified challenge submissions.'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='pillar3_title',
            field=models.CharField(default='Grow', max_length=100),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='speaker_series_badge',
            field=models.CharField(default='Speaker Series', max_length=80),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='speaker_series_description',
            field=models.TextField(default='Hear how fellow CS students build notable projects, secure internships, and prepare for tech careers.'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='speaker_series_title',
            field=models.CharField(default='Tell Your Story · Bi-Weekly Student Stage', max_length=200),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='spotlight_heading',
            field=models.CharField(default='CSS Spotlight & Journal', max_length=200),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='spotlight_subheading',
            field=models.CharField(default='Insights, project writeups, and student reflections.', max_length=255),
        ),
    ]
