# Generated by Django 6.1.1 on 2026-09-21 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0010_siteconfiguration_challenges_heading_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='activities_heading',
            field=models.CharField(default='Upcoming Activities', max_length=200),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='activities_page_lead',
            field=models.TextField(default='Learn together, meet new people, and put your skills into practice.'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='activities_page_title',
            field=models.CharField(default='Activities & Events', max_length=200),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='activities_subheading',
            field=models.CharField(default='Workshops, study jams, and community sessions.', max_length=255),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='blog_page_lead',
            field=models.TextField(default='Tutorials, learning notes, engineering insights, and career stories from our student builders.'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='blog_page_title',
            field=models.CharField(default='The CSS Journal', max_length=200),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='challenges_page_lead',
            field=models.TextField(default='Build real projects, solve engineering prompts, and showcase your GitHub repositories.'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='challenges_page_title',
            field=models.CharField(default='Coding & Design Challenges', max_length=200),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='clinic_page_lead',
            field=models.TextField(default='Free hardware diagnostics, Linux dual-boot installations, developer environment setup, and thermal maintenance run by senior CS student technicians.'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='clinic_page_title',
            field=models.CharField(default='PC Clinic & Diagnostic Sessions', max_length=200),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='community_page_lead',
            field=models.TextField(default='Explore specialized engineering tracks, participate in hands-on study groups, work on open-source projects, and accelerate your tech career alongside peer builders.'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='community_page_title',
            field=models.CharField(default='Join a Technical Community', max_length=200),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='executives_page_lead',
            field=models.TextField(default="These passionate leaders guide the society's mission, organize technical programs, foster partnerships, and champion initiatives that benefit our members."),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='executives_page_title',
            field=models.CharField(default='Meet the Executives', max_length=200),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='future_lab_badge',
            field=models.CharField(default='Future Lab · Ideas Happen Here', help_text='Badge text overlaid on the Future Lab photo', max_length=150),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='future_lab_image',
            field=models.ImageField(blank=True, help_text='Future Lab or Hero section photo (fallback: static/images/images (1).jpeg)', null=True, upload_to='site_config/'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='internships_page_lead',
            field=models.TextField(default='Verified student roles, internships, and entry-level engineering opportunities shared with CSS members.'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='internships_page_title',
            field=models.CharField(default='Internships & Career Opportunities', max_length=200),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='leaderboard_page_lead',
            field=models.TextField(default='Top contributors, active challenge solvers, and community champions.'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='leaderboard_page_title',
            field=models.CharField(default='Society Leaderboard', max_length=200),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='site_logo',
            field=models.ImageField(blank=True, help_text='Site navbar logo (fallback: static/images/com.png)', null=True, upload_to='site_config/'),
        ),
    ]
